name: actions_file

on:
  schedule:
    # this is for every two hours '*/2 * * * *' for every two minutes; refer "crontab.guru"
    - cron: "0 */2 * * *" 
    # This allows manual triggering
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
      # check out the repository content to github runner
        uses: actions/checkout@v4 
        with:
          persist-credentials: false # Optional: Avoid using GitHub token for submodules
          fetch-depth: 0 # Fetch all history for tags and branches

      - name: Test connection
        run: curl -I https://github.com

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.6" 
          # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if connection string is set
        run: |
          if [ -z "$connection_string" ]; then
            echo "Connection string is not set!"
            exit 1
          else
            echo "Connection string is set."
          fi
        
        env:
          connection_string: ${{ secrets.CONNECTION_STRING }}

      - name: execute py script 
      # run app.py
        env:
          connection_string: ${{ secrets.CONNECTION_STRING }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_STEP_DEBUG: true
        run: python app.py
