name: python_cron_job

on:
    schedule:
        - cron: '* */2 * * *'  # this is for every two hours '*/2 * * * *' for every two minutes; refer "crontab.guru"
    workflow_dispatch:   # This allows manual triggering

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: check out repo
              uses: actions/checkout@<SHA>  # check out the repository content to github runner
              
            - name: Test connection 
              run: curl -I https://github.com

            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'  # install the python version needed
            
            - name: install python packages
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: execute py script # run app.py
              env:
                connection_string: ${{secrets.CONNECTION_STRING}}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                ACTIONS_STEP_DEBUG: true
              run: python app.py

    
